apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  source:
    chart: grafana
    repoURL: "https://grafana.github.io/helm-charts"
    targetRevision: 6.58.4
    helm:
      releaseName: grafana
      valuesObject:
        ingress:
          enabled: true
          path: /
          hosts:
            - grafana.local
  destination:
    server: "https://kubernetes.default.svc"
    namespace: grafana
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
