apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: default
  sources:
  - chart: "kube-prometheus-stack"
    repoURL: "https://prometheus-community.github.io/helm-charts"
    targetRevision: 4.81.1
    helm:
      releaseName: prometheus
      version: v3
      valueFiles:
        - "$values/charts/prometheus/values.yaml"
  - repoURL: 'https://github.com/mmpyro/helmcharts.git'
    targetRevision: "HEAD"
    ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
