apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: busybox
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/mmpyro/helmcharts.git"
    targetRevision: 'HEAD'
    path: charts/busybox
    helm:
      valueFiles:
        - values.yaml
      version: v3
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true