apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress
  namespace: argocd
spec:
  project: default
  source:
    chart: nginx-ingress
    repoURL: oci://ghcr.io/nginxinc/charts/nginx-ingress
    targetRevision: 0.18.0
    helm:
      releaseName: nginx-ingress
  destination:
    server: "https://kubernetes.default.svc"
